/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_audit_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_backups"];
        put?: never;
        post: operations["create_backup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_channels"];
        put?: never;
        post: operations["create_channel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/channels/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["import_channels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_channel"];
        put: operations["update_channel"];
        post?: never;
        delete: operations["delete_channel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/channels/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["change_channel_status"];
        trace?: never;
    };
    "/api/v1/admin/channels/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_channel_versions"];
        put?: never;
        post: operations["create_new_channel_version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_connectors"];
        put?: never;
        post: operations["create_connector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/connectors/circuit-breakers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_circuit_breakers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/connectors/circuit-breakers/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reset_circuit_breaker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/connectors/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["import_connectors"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/connectors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_connector"];
        put: operations["update_connector"];
        post?: never;
        delete: operations["delete_connector"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/engine/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["engine_reload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/engine/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["engine_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/functions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_functions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_workflows"];
        put?: never;
        post: operations["create_workflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/workflows/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["export_workflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/workflows/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["import_workflows"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/workflows/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validate_workflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/workflows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_workflow"];
        put: operations["update_workflow"];
        post?: never;
        delete: operations["delete_workflow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/workflows/{id}/rollout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_rollout"];
        trace?: never;
    };
    "/api/v1/admin/workflows/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["change_workflow_status"];
        trace?: never;
    };
    "/api/v1/admin/workflows/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test_workflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/workflows/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_workflow_versions"];
        put?: never;
        post: operations["create_new_workflow_version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_traces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/traces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_trace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["metrics_endpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Channel: {
            channel_id: string;
            channel_type: string;
            config_json: string;
            consumer_group?: string | null;
            /** Format: date-time */
            created_at: string;
            description?: string | null;
            methods?: string | null;
            name: string;
            /** Format: int64 */
            priority: number;
            protocol: string;
            route_pattern?: string | null;
            status: string;
            topic?: string | null;
            transport_config_json: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            version: number;
            workflow_id?: string | null;
        };
        /** @enum {string} */
        ChannelProtocol: "rest" | "http" | "kafka";
        ChannelStatusChangeRequest: {
            status: components["schemas"]["EntityStatus"];
        };
        /** @enum {string} */
        ChannelType: "sync" | "async";
        Connector: {
            config_json: string;
            connector_type: string;
            /** Format: date-time */
            created_at: string;
            enabled: boolean;
            id: string;
            name: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Typed enum for the connector `type` field on create/update requests.
         *     Wire format is lowercase ("http", "kafka", "db", "cache", "storage");
         *     deserialization is case-insensitive so "HTTP" or "Kafka" also parse —
         *     strictly additive on v0.1's accepted set.
         * @enum {string}
         */
        ConnectorType: "http" | "kafka" | "db" | "cache" | "storage" | "es";
        CreateChannelRequest: {
            channel_id?: string | null;
            channel_type: components["schemas"]["ChannelType"];
            config?: unknown;
            consumer_group?: string | null;
            description?: string | null;
            methods?: string[] | null;
            name: string;
            /** Format: int64 */
            priority?: number;
            protocol: components["schemas"]["ChannelProtocol"];
            route_pattern?: string | null;
            topic?: string | null;
            transport_config?: unknown;
            workflow_id?: string | null;
        };
        CreateConnectorRequest: {
            config?: unknown;
            connector_type: components["schemas"]["ConnectorType"];
            id?: string | null;
            name: string;
        };
        CreateWorkflowRequest: {
            condition?: unknown;
            continue_on_error?: boolean;
            description?: string | null;
            name: string;
            /** Format: int64 */
            priority?: number;
            tags?: string[];
            tasks: unknown;
            workflow_id?: string | null;
        };
        /** @enum {string} */
        EntityStatus: "draft" | "active" | "archived";
        ErrorDetail: {
            code: string;
            message: string;
        };
        /** @description Error response body matching Orion's `{"error": {"code": "...", "message": "..."}}` format. */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        ProcessRequest: {
            data: unknown;
            metadata?: unknown;
        };
        RolloutUpdateRequest: {
            /** Format: int64 */
            rollout_percentage: number;
        };
        StatusChangeRequest: {
            /** Format: int64 */
            rollout_percentage?: number | null;
            status: components["schemas"]["EntityStatus"];
        };
        TestWorkflowRequest: {
            data: unknown;
            metadata?: unknown;
        };
        Trace: {
            channel: string;
            channel_id?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: double */
            duration_ms?: number | null;
            error_message?: string | null;
            id: string;
            input_json?: string | null;
            mode: string;
            result_json?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            status: string;
            /**
             * @description Per-task `dataflow_rs::ExecutionTrace` JSON, captured only when the
             *     channel has `config.tracing.task_details = true`. Workflow authors
             *     can inspect intermediate inputs/outputs for each task to debug
             *     pipelines without re-running them in dry-run.
             */
            task_trace_json?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        UpdateChannelRequest: {
            config?: unknown;
            consumer_group?: string | null;
            description?: string | null;
            methods?: string[] | null;
            name?: string | null;
            /** Format: int64 */
            priority?: number | null;
            route_pattern?: string | null;
            topic?: string | null;
            transport_config?: unknown;
            workflow_id?: string | null;
        };
        UpdateConnectorRequest: {
            config?: unknown;
            connector_type?: null | components["schemas"]["ConnectorType"];
            enabled?: boolean | null;
            name?: string | null;
        };
        UpdateWorkflowRequest: {
            condition?: unknown;
            continue_on_error?: boolean | null;
            description?: string | null;
            name?: string | null;
            /** Format: int64 */
            priority?: number | null;
            tags?: string[] | null;
            tasks?: unknown;
        };
        ValidationIssue: {
            field: string;
            message: string;
        };
        ValidationResponse: {
            errors: components["schemas"]["ValidationIssue"][];
            valid: boolean;
            warnings: components["schemas"]["ValidationIssue"][];
        };
        Workflow: {
            condition_json: string;
            continue_on_error: boolean;
            /** Format: date-time */
            created_at: string;
            description?: string | null;
            name: string;
            /** Format: int64 */
            priority: number;
            /** Format: int64 */
            rollout_percentage: number;
            status: string;
            tags: string;
            tasks_json: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            version: number;
            workflow_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_logs: {
        parameters: {
            query?: {
                /** @description Pagination offset (default 0) */
                offset?: number;
                /** @description Page size, clamped to [1, 1000] (default 50) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated audit log entries with total count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_backups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of backup files in the configured backup directory */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_backup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup created (SQLite only — VACUUM INTO a timestamped file) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backup unavailable (non-SQLite backend) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_channels: {
        parameters: {
            query?: {
                status?: string | null;
                channel_type?: string | null;
                protocol?: string | null;
                limit?: number | null;
                offset?: number | null;
                /** @description Column to sort by: priority (default), name, status, channel_type, protocol, created_at, updated_at. */
                sort_by?: string | null;
                /** @description Sort direction: asc or desc (default). */
                sort_order?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of channels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_channel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChannelRequest"];
            };
        };
        responses: {
            /** @description Channel created as draft */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    import_channels: {
        parameters: {
            query?: {
                /**
                 * @description When true, validates each item and reports what would happen
                 *     without writing to the database. The response shape mirrors
                 *     a real import but `imported` is always 0.
                 */
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChannelRequest"][];
            };
        };
        responses: {
            /** @description Import results with counts (or would-be results when ?dry_run=true). Dry-run validates each item's shape and values only — it does NOT read the database, so it cannot detect name conflicts. Channels whose names already exist are reported as would_create and will surface as Conflict on the real (non-dry-run) import. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_channel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Channel not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_channel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChannelRequest"];
            };
        };
        responses: {
            /** @description Draft channel updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No draft version or invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Channel not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_channel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Channel not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_channel_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelStatusChangeRequest"];
            };
        };
        responses: {
            /** @description Status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid status transition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Channel not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_channel_versions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated version history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Channel not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_new_channel_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New draft version created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Draft already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_connectors: {
        parameters: {
            query?: {
                limit?: number | null;
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of connectors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_connector: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnectorRequest"];
            };
        };
        responses: {
            /** @description Connector created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Connector name conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_circuit_breakers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Circuit breaker states */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reset_circuit_breaker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Circuit breaker key (channel:connector) */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Circuit breaker reset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Circuit breaker not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    import_connectors: {
        parameters: {
            query?: {
                /**
                 * @description When true, validates each item and reports what would happen
                 *     without writing to the database. The response shape mirrors
                 *     a real import but `imported` is always 0.
                 */
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnectorRequest"][];
            };
        };
        responses: {
            /** @description Import results with counts (or would-be results when ?dry_run=true). Dry-run validates each item's shape and values only — it does NOT read the database, so it cannot detect name conflicts. Connectors whose names already exist are reported as would_create and will surface as Conflict on the real (non-dry-run) import. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_connector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connector ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connector details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Connector not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_connector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connector ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConnectorRequest"];
            };
        };
        responses: {
            /** @description Connector updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Connector not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_connector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connector ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connector deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Connector not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    engine_reload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Engine reloaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    engine_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Engine status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_functions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered workflow function schemas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_workflows: {
        parameters: {
            query?: {
                status?: string | null;
                tag?: string | null;
                limit?: number | null;
                offset?: number | null;
                /** @description Column to sort by: priority (default), name, status, created_at, updated_at. */
                sort_by?: string | null;
                /** @description Sort direction: asc or desc (default). */
                sort_order?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of workflows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_workflow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowRequest"];
            };
        };
        responses: {
            /** @description Workflow created as draft */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export_workflows: {
        parameters: {
            query?: {
                status?: string | null;
                tag?: string | null;
                limit?: number | null;
                offset?: number | null;
                /** @description Column to sort by: priority (default), name, status, created_at, updated_at. */
                sort_by?: string | null;
                /** @description Sort direction: asc or desc (default). */
                sort_order?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exported workflows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    import_workflows: {
        parameters: {
            query?: {
                /**
                 * @description When true, validates each item and reports what would happen
                 *     without writing to the database. The response shape mirrors
                 *     a real import but `imported` is always 0.
                 */
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowRequest"][];
            };
        };
        responses: {
            /** @description Import results with counts (or would-be results when ?dry_run=true) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    validate_workflow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowRequest"];
            };
        };
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
        };
    };
    get_workflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workflow ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workflow not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_workflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workflow ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkflowRequest"];
            };
        };
        responses: {
            /** @description Draft workflow updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No draft version or invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workflow not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_workflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workflow ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workflow not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_rollout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workflow ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolloutUpdateRequest"];
            };
        };
        responses: {
            /** @description Rollout percentage updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid rollout configuration */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_workflow_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workflow ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChangeRequest"];
            };
        };
        responses: {
            /** @description Status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid status transition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workflow not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    test_workflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workflow ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestWorkflowRequest"];
            };
        };
        responses: {
            /** @description Test result with trace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workflow not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_workflow_versions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workflow ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated version history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workflow not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_new_workflow_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workflow ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New draft version created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Draft already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_traces: {
        parameters: {
            query?: {
                /** @description Filter by trace status */
                status?: string;
                /** @description Filter by channel */
                channel?: string;
                /** @description Filter by mode: sync, async */
                mode?: string;
                /** @description Page size (default 50, max 1000) */
                limit?: number;
                /** @description Page offset */
                offset?: number;
                /** @description Sort column: created_at (default), updated_at, status, channel, mode */
                sort_by?: string;
                /** @description Sort direction: asc or desc (default) */
                sort_order?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of traces */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_trace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trace ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trace status and result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Trace not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service degraded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    metrics_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
        };
    };
}
